name: Update From Template

on:
  push:
    branches:
      - main 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch template updates
      run: |
        git remote add template https://github.com/bianshuyang/Summer_Validate_00.git
        git fetch template
        # list of files to be fetched
        files_to_update=(
          "3.in"
          "3.ans"
          # add more files as needed
        )
        for file in "${files_to_update[@]}"; do
          git checkout template/main -- "$file"
        done

    - name: Commit and push if it changed
      run: |
        git config --global user.name "Dooley the Skeleton"
        git config --global user.email "dooleytheskeleton@exaaaaample.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "Automated update from template"
        git push
